-- feat/meal-planner — weekly meal planner storage.
-- meal_slot is TEXT + CHECK (same pattern as cooked.user_settings.kcal_mode),
-- which avoids Postgres-enum/Hibernate casting friction on derived queries.
-- Run as the admin user against the `cooked` database (DDL):
--
--   psql -U postgres -d cooked -f db/feat-meal-planner/01_meal_plan.sql
--
-- Idempotent: safe to re-run (IF NOT EXISTS).

-- weekly meal planner: recipes assigned to a (date, slot); multiple per slot
CREATE TABLE IF NOT EXISTS cooked.meal_plan (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  plan_date  DATE NOT NULL,
  meal_slot  TEXT NOT NULL CHECK (meal_slot IN ('breakfast', 'lunch', 'snack', 'dinner')),
  recipe_id  BIGINT NOT NULL REFERENCES cooked.recipe(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, plan_date, meal_slot, recipe_id)
);
CREATE INDEX IF NOT EXISTS ix_meal_plan_user_date ON cooked.meal_plan(user_id, plan_date);
CREATE INDEX IF NOT EXISTS ix_meal_plan_recipe    ON cooked.meal_plan(recipe_id);

-- app role grants (default privileges usually cover this; explicit for standalone runs)
GRANT SELECT, INSERT, UPDATE, DELETE ON cooked.meal_plan TO cooked_user;
GRANT SELECT ON cooked.meal_plan TO cooked_readonly;
