spring.application.name=cooked-service

server.forward-headers-strategy=FRAMEWORK
server.port=${SERVER_PORT:8082}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.jpa.properties.hibernate.default_schema=cooked_service

# Database Connection
spring.datasource.url=${CUSTOM_DB_URL}
spring.datasource.username=${CUSTOM_DB_USER}
spring.datasource.password=${CUSTOM_DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET search_path TO cooked_service

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

application.servicename=Cooked