-- feat/pantry-templates — reusable saved pantry ingredient lists.
-- A template stores ONLY ingredient references (names) for a user — no
-- quantity/unit/expiration. Loading a template (frontend) adds each ingredient
-- to the pantry with qty 0 and no expiry for the user to fill in.
-- Run as the admin user against the `cooked` database (DDL):
--
--   psql -U postgres -d cooked -f db/feat-pantry-templates/01_pantry_template.sql
--
-- Idempotent: safe to re-run (IF NOT EXISTS).

-- one named template per row, scoped to a user
CREATE TABLE IF NOT EXISTS cooked.pantry_template (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pantry_template_user ON cooked.pantry_template(user_id);

-- ingredients that belong to a template; PK dedupes a name within one template
CREATE TABLE IF NOT EXISTS cooked.pantry_template_item (
  template_id   BIGINT NOT NULL REFERENCES cooked.pantry_template(id) ON DELETE CASCADE,
  ingredient_id BIGINT NOT NULL REFERENCES cooked.ingredient(id) ON DELETE CASCADE,
  PRIMARY KEY (template_id, ingredient_id)
);
CREATE INDEX IF NOT EXISTS ix_pantry_template_item_ing ON cooked.pantry_template_item(ingredient_id);

-- app role grants (default privileges usually cover this; explicit for standalone runs)
GRANT SELECT, INSERT, UPDATE, DELETE ON cooked.pantry_template      TO cooked_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON cooked.pantry_template_item TO cooked_user;
GRANT SELECT ON cooked.pantry_template      TO cooked_readonly;
GRANT SELECT ON cooked.pantry_template_item TO cooked_readonly;
