-- Cooked — canonical fresh-install schema (single source of truth)
-- Schema: cooked
-- PostgreSQL 14+
--
-- This is THE canonical schema for both cooked-service and cooked-ui.
-- The cooked-ui repo no longer carries a setup.sql — all schema changes
-- and migrations live in this repo under db/.
--
-- Plain SQL only (no psql meta-commands) — runs in psql, DBeaver, IntelliJ,
-- or any other client. Create the database first (CREATE DATABASE cooked;),
-- then run this against it as a superuser:
--
--   psql -U postgres -d cooked -f db/setup.sql
--
-- Passwords are NEVER checked in. Roles are created with CHANGE_ME
-- placeholder passwords — set the real ones immediately afterwards:
--
--   ALTER ROLE cooked_user     PASSWORD '<app password>';
--   ALTER ROLE cooked_readonly PASSWORD '<readonly password>';
--
-- (Existing roles are never altered or dropped by this script, so
-- re-running it will not reset rotated passwords.)
--
-- Idempotent: safe to re-run against an already-deployed database.

-- ──────────────────────────────────────────────
-- Roles (login users)
-- ──────────────────────────────────────────────

-- cooked_user: the Spring Boot application user (full CRUD, no DDL)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cooked_user') THEN
    CREATE ROLE cooked_user LOGIN PASSWORD 'CHANGE_ME';
  END IF;
END $$;

-- cooked_readonly: reporting / debugging user (SELECT only)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cooked_readonly') THEN
    CREATE ROLE cooked_readonly LOGIN PASSWORD 'CHANGE_ME';
  END IF;
END $$;

GRANT CONNECT ON DATABASE cooked TO cooked_user;
GRANT CONNECT ON DATABASE cooked TO cooked_readonly;

-- ──────────────────────────────────────────────
-- Schema & types
-- ──────────────────────────────────────────────

CREATE SCHEMA IF NOT EXISTS cooked;

-- pantry quantity units; everything converts to grams in app logic
-- (pcs via ingredient.grams_per_piece, ml/L treated as g/kg)
DO $$ BEGIN
  CREATE TYPE cooked.unit_type AS ENUM ('g', 'kg', 'ml', 'L', 'pcs');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ──────────────────────────────────────────────
-- Tables
-- ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS cooked.app_user (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  display_name  TEXT NOT NULL,
  handle        TEXT UNIQUE,                      -- community handle, e.g. @priya.kitchen
  password_hash TEXT,                             -- BCrypt; NULL only for legacy/seed display users
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- fixed vocabularies (seeded; FK targets so typos can't creep in)
CREATE TABLE IF NOT EXISTS cooked.mood (
  name TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS cooked.cuisine (
  name TEXT PRIMARY KEY
);

-- ingredient database: built-ins (is_builtin) + user-created (created_by)
CREATE TABLE IF NOT EXISTS cooked.ingredient (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  name            TEXT NOT NULL UNIQUE,
  category        TEXT NOT NULL,
  kcal_per_gram   NUMERIC(8,4) NOT NULL CHECK (kcal_per_gram >= 0),
  grams_per_piece NUMERIC(8,2) CHECK (grams_per_piece > 0), -- NULL unless countable (pcs)
  is_builtin      BOOLEAN NOT NULL DEFAULT FALSE,
  created_by      BIGINT REFERENCES cooked.app_user(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_ingredient_created_by ON cooked.ingredient(created_by);
CREATE INDEX IF NOT EXISTS ix_ingredient_category   ON cooked.ingredient(category);

-- per-user calorie overrides of built-in ingredients (overlay, never mutate built-ins)
CREATE TABLE IF NOT EXISTS cooked.user_ingredient_edit (
  user_id         BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  ingredient_id   BIGINT NOT NULL REFERENCES cooked.ingredient(id) ON DELETE CASCADE,
  kcal_per_gram   NUMERIC(8,4) CHECK (kcal_per_gram >= 0),
  grams_per_piece NUMERIC(8,2) CHECK (grams_per_piece > 0),
  PRIMARY KEY (user_id, ingredient_id)
);
CREATE INDEX IF NOT EXISTS ix_user_ingredient_edit_ingredient ON cooked.user_ingredient_edit(ingredient_id);

-- recipes: built-ins (owner NULL, author_label 'Chef …'), community seeds
-- (owner NULL, is_community, author_label '@handle'), and user recipes
-- (owner set; is_shared publishes them to the community feed)
CREATE TABLE IF NOT EXISTS cooked.recipe (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  name          TEXT NOT NULL,
  owner_user_id BIGINT REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  author_label  TEXT,                              -- display author when owner is NULL
  cuisine       TEXT NOT NULL REFERENCES cooked.cuisine(name),
  prep_time_min INTEGER NOT NULL CHECK (prep_time_min > 0),
  servings      INTEGER NOT NULL CHECK (servings > 0),
  is_community  BOOLEAN NOT NULL DEFAULT FALSE,
  is_shared     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- built-in / community-seed names are unique; user recipe names are per-user free
CREATE UNIQUE INDEX IF NOT EXISTS ux_recipe_builtin_name
  ON cooked.recipe (lower(name)) WHERE owner_user_id IS NULL;
CREATE INDEX IF NOT EXISTS ix_recipe_owner   ON cooked.recipe(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_recipe_cuisine ON cooked.recipe(cuisine);

CREATE TABLE IF NOT EXISTS cooked.recipe_mood (
  recipe_id BIGINT NOT NULL REFERENCES cooked.recipe(id) ON DELETE CASCADE,
  mood      TEXT   NOT NULL REFERENCES cooked.mood(name),
  PRIMARY KEY (recipe_id, mood)
);

CREATE TABLE IF NOT EXISTS cooked.recipe_ingredient (
  recipe_id     BIGINT NOT NULL REFERENCES cooked.recipe(id) ON DELETE CASCADE,
  ingredient_id BIGINT NOT NULL REFERENCES cooked.ingredient(id) ON DELETE RESTRICT,
  grams         NUMERIC(8,2) NOT NULL CHECK (grams > 0),
  PRIMARY KEY (recipe_id, ingredient_id)
);
CREATE INDEX IF NOT EXISTS ix_recipe_ingredient_ingredient ON cooked.recipe_ingredient(ingredient_id);

-- ordered cooking steps for a recipe
CREATE TABLE IF NOT EXISTS cooked.recipe_instruction (
  recipe_id   BIGINT   NOT NULL REFERENCES cooked.recipe(id) ON DELETE CASCADE,
  step_no     SMALLINT NOT NULL CHECK (step_no > 0),
  instruction TEXT     NOT NULL,
  PRIMARY KEY (recipe_id, step_no)
);

-- community recipes a user saved into their kitchen
CREATE TABLE IF NOT EXISTS cooked.saved_recipe (
  user_id   BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  recipe_id BIGINT NOT NULL REFERENCES cooked.recipe(id) ON DELETE CASCADE,
  saved_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, recipe_id)
);
CREATE INDEX IF NOT EXISTS ix_saved_recipe_recipe ON cooked.saved_recipe(recipe_id);

-- pantry: one row per purchased lot (same ingredient can appear multiple
-- times with different expirations; cooking deducts earliest-expiring first)
CREATE TABLE IF NOT EXISTS cooked.pantry_item (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  user_id       BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  ingredient_id BIGINT NOT NULL REFERENCES cooked.ingredient(id) ON DELETE RESTRICT,
  qty           NUMERIC(10,3) NOT NULL CHECK (qty >= 0),
  unit          cooked.unit_type NOT NULL DEFAULT 'g',
  expires_on    DATE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_pantry_item_user_exp    ON cooked.pantry_item(user_id, expires_on);
CREATE INDEX IF NOT EXISTS ix_pantry_item_ingredient  ON cooked.pantry_item(ingredient_id);

CREATE TABLE IF NOT EXISTS cooked.shopping_item (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  user_id       BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  ingredient_id BIGINT NOT NULL REFERENCES cooked.ingredient(id) ON DELETE RESTRICT,
  grams         NUMERIC(10,2) NOT NULL CHECK (grams > 0),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, ingredient_id)
);
CREATE INDEX IF NOT EXISTS ix_shopping_item_ingredient ON cooked.shopping_item(ingredient_id);

-- cooking log; ingredient names/kcal are snapshots so history survives
-- recipe edits, deletions, and calorie-database changes
CREATE TABLE IF NOT EXISTS cooked.cook_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  recipe_id   BIGINT REFERENCES cooked.recipe(id) ON DELETE SET NULL,
  recipe_name TEXT NOT NULL,
  scale       NUMERIC(6,2)  NOT NULL DEFAULT 1 CHECK (scale > 0),
  servings    NUMERIC(6,2)  NOT NULL CHECK (servings > 0),
  total_kcal  NUMERIC(10,2) NOT NULL CHECK (total_kcal >= 0),
  cooked_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_cook_history_user_time ON cooked.cook_history(user_id, cooked_at DESC);
CREATE INDEX IF NOT EXISTS ix_cook_history_recipe    ON cooked.cook_history(recipe_id);

CREATE TABLE IF NOT EXISTS cooked.cook_history_item (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
  cook_history_id BIGINT NOT NULL REFERENCES cooked.cook_history(id) ON DELETE CASCADE,
  ingredient_name TEXT NOT NULL,
  grams           NUMERIC(10,2) NOT NULL CHECK (grams > 0),
  kcal            NUMERIC(10,2) NOT NULL CHECK (kcal >= 0)
);
CREATE INDEX IF NOT EXISTS ix_cook_history_item_history ON cooked.cook_history_item(cook_history_id);

-- per-user app settings (mirrors the frontend Settings + kcalGoal)
CREATE TABLE IF NOT EXISTS cooked.user_settings (
  user_id    BIGINT PRIMARY KEY REFERENCES cooked.app_user(id) ON DELETE CASCADE,
  accent     TEXT NOT NULL DEFAULT '#C2552F',
  kcal_mode  TEXT NOT NULL DEFAULT 'per serving'
             CHECK (kcal_mode IN ('per serving', 'whole recipe')),
  ready_only BOOLEAN NOT NULL DEFAULT FALSE,
  kcal_goal  INTEGER NOT NULL DEFAULT 2000 CHECK (kcal_goal >= 0)
);

-- ──────────────────────────────────────────────
-- Permissions
-- ──────────────────────────────────────────────

GRANT USAGE ON SCHEMA cooked TO cooked_user;
GRANT USAGE ON SCHEMA cooked TO cooked_readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA cooked TO cooked_user;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA cooked TO cooked_user;

GRANT SELECT ON ALL TABLES IN SCHEMA cooked TO cooked_readonly;

-- future tables created by the admin/migration user inherit the same grants
ALTER DEFAULT PRIVILEGES IN SCHEMA cooked
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cooked_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cooked
  GRANT USAGE, SELECT ON SEQUENCES TO cooked_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cooked
  GRANT SELECT ON TABLES TO cooked_readonly;

ALTER ROLE cooked_user     IN DATABASE cooked SET search_path = cooked, public;
ALTER ROLE cooked_readonly IN DATABASE cooked SET search_path = cooked, public;
