-- Cooked Service — full schema
-- Schema: cooked
-- PostgreSQL 14+
--
-- Run as a superuser (e.g. postgres):
--   psql -U postgres -d cooked -f db/setup.sql
--
-- IMPORTANT: Never check in real passwords.
-- Replace CHANGE_ME with the actual password immediately after running.

-- ──────────────────────────────────────────────
-- Roles
-- ──────────────────────────────────────────────
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE usename = 'cooked_user';

REVOKE ALL PRIVILEGES ON ALL TABLES    IN SCHEMA cooked FROM cooked_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cooked FROM cooked_user;
REVOKE ALL ON SCHEMA cooked FROM cooked_user;
REVOKE CONNECT ON DATABASE cooked FROM cooked_user;
DROP USER IF EXISTS cooked_user;

CREATE USER cooked_user WITH PASSWORD 'CHANGE_ME';

-- ──────────────────────────────────────────────
-- Schema
-- ──────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS cooked;

GRANT CONNECT  ON DATABASE cooked    TO cooked_user;
GRANT USAGE    ON SCHEMA cooked      TO cooked_user;
GRANT CREATE   ON SCHEMA cooked      TO cooked_user;

SET search_path TO cooked;

-- ──────────────────────────────────────────────
-- Enum types
-- ──────────────────────────────────────────────
DO $$ BEGIN
    CREATE TYPE unit_type AS ENUM ('g','kg','ml','L','pcs');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ──────────────────────────────────────────────
-- Tables
-- ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS app_user (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    display_name  VARCHAR(100) NOT NULL,
    handle        VARCHAR(50)  UNIQUE,
    password_hash TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mood (
    name  VARCHAR(50) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS cuisine (
    name  VARCHAR(100) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS ingredient (
    id             BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(150)    NOT NULL UNIQUE,
    category       VARCHAR(100)    NOT NULL,
    kcal_per_gram  NUMERIC(6,3)    NOT NULL,
    grams_per_piece NUMERIC(8,2),
    is_builtin     BOOLEAN         NOT NULL DEFAULT FALSE,
    created_by     BIGINT          REFERENCES app_user (id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_ingredient_edit (
    user_id         BIGINT       NOT NULL REFERENCES app_user  (id) ON DELETE CASCADE,
    ingredient_id   BIGINT       NOT NULL REFERENCES ingredient (id) ON DELETE CASCADE,
    kcal_per_gram   NUMERIC(6,3),
    grams_per_piece NUMERIC(8,2),
    PRIMARY KEY (user_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS recipe (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    owner_user_id BIGINT       REFERENCES app_user (id) ON DELETE SET NULL,
    author_label  VARCHAR(100),
    cuisine       VARCHAR(100) NOT NULL REFERENCES cuisine (name),
    prep_time_min INTEGER      NOT NULL,
    servings      INTEGER      NOT NULL,
    is_community  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_shared     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recipe_owner ON recipe (owner_user_id);

CREATE TABLE IF NOT EXISTS recipe_mood (
    recipe_id BIGINT      NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    mood      VARCHAR(50) NOT NULL REFERENCES mood   (name),
    PRIMARY KEY (recipe_id, mood)
);

CREATE TABLE IF NOT EXISTS recipe_ingredient (
    recipe_id     BIGINT       NOT NULL REFERENCES recipe     (id) ON DELETE CASCADE,
    ingredient_id BIGINT       NOT NULL REFERENCES ingredient  (id),
    grams         NUMERIC(8,2) NOT NULL,
    PRIMARY KEY (recipe_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS recipe_instruction (
    recipe_id   BIGINT       NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    step_no     SMALLINT     NOT NULL,
    instruction TEXT         NOT NULL,
    PRIMARY KEY (recipe_id, step_no)
);

CREATE TABLE IF NOT EXISTS saved_recipe (
    user_id    BIGINT      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    recipe_id  BIGINT      NOT NULL REFERENCES recipe   (id) ON DELETE CASCADE,
    saved_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, recipe_id)
);

CREATE TABLE IF NOT EXISTS pantry_item (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES app_user  (id) ON DELETE CASCADE,
    ingredient_id BIGINT      NOT NULL REFERENCES ingredient (id),
    qty           NUMERIC(10,3) NOT NULL,
    unit          unit_type   NOT NULL DEFAULT 'g',
    expires_on    DATE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pantry_user ON pantry_item (user_id);

CREATE TABLE IF NOT EXISTS shopping_item (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL REFERENCES app_user  (id) ON DELETE CASCADE,
    ingredient_id BIGINT        NOT NULL REFERENCES ingredient (id),
    grams         NUMERIC(10,2) NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (user_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS cook_history (
    id           BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT          NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    recipe_id    BIGINT          REFERENCES recipe (id) ON DELETE SET NULL,
    recipe_name  VARCHAR(200)    NOT NULL,
    scale        NUMERIC(6,2)    NOT NULL DEFAULT 1,
    servings     NUMERIC(6,2)    NOT NULL,
    total_kcal   NUMERIC(10,2)   NOT NULL,
    cooked_at    TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cook_history_user ON cook_history (user_id);

CREATE TABLE IF NOT EXISTS cook_history_item (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cook_history_id  BIGINT        NOT NULL REFERENCES cook_history (id) ON DELETE CASCADE,
    ingredient_name  VARCHAR(150)  NOT NULL,
    grams            NUMERIC(8,2)  NOT NULL,
    kcal             NUMERIC(8,2)  NOT NULL
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id    BIGINT       PRIMARY KEY REFERENCES app_user (id) ON DELETE CASCADE,
    accent     VARCHAR(20)  NOT NULL DEFAULT '#FF6B35',
    kcal_mode  VARCHAR(20)  NOT NULL DEFAULT 'per serving',
    ready_only BOOLEAN      NOT NULL DEFAULT FALSE,
    kcal_goal  INTEGER      NOT NULL DEFAULT 2000
);

-- ──────────────────────────────────────────────
-- Grants (re-run after table creation)
-- ──────────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA cooked TO cooked_user;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA cooked TO cooked_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA cooked
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO cooked_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cooked
    GRANT USAGE, SELECT                  ON SEQUENCES TO cooked_user;
