-- Cooked Service — full schema
-- Schema: cooked_service
-- PostgreSQL 14+
--
-- Run as a superuser (e.g. postgres):
--   psql -U postgres -d cooked -f db/setup.sql

-- ──────────────────────────────────────────────
-- User & roles
-- ──────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS cooked_service;

-- 1. Terminate active connections
SELECT pg_terminate_backend(pid)
FROM pg_stat_activity
WHERE usename = 'cooked_user';

-- 2. Revoke all privileges first
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA cooked_service FROM cooked_user;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA cooked_service FROM cooked_user;
REVOKE ALL ON SCHEMA cooked_service FROM cooked_user;
REVOKE CONNECT ON DATABASE cooked FROM cooked_user;

-- 3. Drop the user
DROP USER IF EXISTS cooked_user;
-- ──────────────────────────────────────────────

CREATE USER cooked_user WITH PASSWORD 'Password123!';

GRANT CONNECT ON DATABASE cooked TO cooked_user;

GRANT USAGE  ON SCHEMA cooked_service TO cooked_user;
GRANT CREATE ON SCHEMA cooked_service TO cooked_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA cooked_service TO cooked_user;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA cooked_service TO cooked_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA cooked_service
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES    TO cooked_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA cooked_service
    GRANT USAGE, SELECT                  ON SEQUENCES TO cooked_user;

SET search_path TO cooked_service;

-- ──────────────────────────────────────────────
-- Enum types
-- ──────────────────────────────────────────────

CREATE TYPE difficulty_t AS ENUM ('easy','medium','hard');

-- ──────────────────────────────────────────────
-- Tables
-- ──────────────────────────────────────────────

CREATE TABLE users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE recipe (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
    user_id       INTEGER      NOT NULL REFERENCES users (id),
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(1000),
    cuisine       VARCHAR(100),
    difficulty    difficulty_t NOT NULL DEFAULT 'easy',
    prep_minutes  INTEGER,
    cook_minutes  INTEGER,
    servings      INTEGER,
    instructions  TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_recipe_user_id ON recipe (user_id);

CREATE TABLE ingredient (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100000) PRIMARY KEY,
    recipe_id INTEGER      NOT NULL REFERENCES recipe (id) ON DELETE CASCADE,
    name      VARCHAR(255) NOT NULL,
    quantity  VARCHAR(50),
    unit      VARCHAR(50),
    position  INTEGER
);

CREATE INDEX idx_ingredient_recipe_id ON ingredient (recipe_id);

-- ──────────────────────────────────────────────
-- updated_at trigger
-- ──────────────────────────────────────────────

CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

CREATE TRIGGER trg_recipe_updated_at
    BEFORE UPDATE ON recipe
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- Re-grant after table creation (defensive — default privileges already cover this)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES    IN SCHEMA cooked_service TO cooked_user;
GRANT USAGE, SELECT                  ON ALL SEQUENCES IN SCHEMA cooked_service TO cooked_user;
